/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TUGAS4;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author ACER
 */
public class POSTTEST4 extends javax.swing.JFrame {
    
    String Nama, NoHp,jenis;
    Integer Berat,Diskon;
    Float Total,uang;
    

    /**
     * Creates new form POSTTEST4
     */
    public POSTTEST4() {
        initComponents();
    }
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom No.Telepon Hanya Bisa Memasukan Karakter Angka");
        }
    }
    void filterangka(KeyEvent b){
        if(Character.isDigit(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Nama Hanya Bisa Memasukan Karakter Huruf");
        }
    }
    void filterhuruff(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom Berat Barang Hanya Bisa Memasukan Karakter Angka");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnjenisjasa = new javax.swing.ButtonGroup();
        pheader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ttelepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tberat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sliderdiskon = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jreguler = new javax.swing.JRadioButton();
        jexpress = new javax.swing.JRadioButton();
        LDiskon = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tatotal = new javax.swing.JTextArea();
        btnproses = new javax.swing.JButton();
        btnulangi = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pheader.setBackground(new java.awt.Color(0, 51, 255));
        pheader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pheaderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pheaderMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel1.setText("                                     Form Pelanggan");

        javax.swing.GroupLayout pheaderLayout = new javax.swing.GroupLayout(pheader);
        pheader.setLayout(pheaderLayout);
        pheaderLayout.setHorizontalGroup(
            pheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pheaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );
        pheaderLayout.setVerticalGroup(
            pheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pheaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(pheader, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel2.setText("Nama");

        tnama.setText("Masukkan Nama");
        tnama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tnamaCaretUpdate(evt);
            }
        });
        tnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnamaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel3.setText("No. Telepon");

        ttelepon.setText("Masukkan No telepon");
        ttelepon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tteleponCaretUpdate(evt);
            }
        });
        ttelepon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tteleponMouseReleased(evt);
            }
        });
        ttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tteleponActionPerformed(evt);
            }
        });
        ttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tteleponKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel4.setText("Berat Barang");

        tberat.setText("??");
        tberat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tberatCaretUpdate(evt);
            }
        });
        tberat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tberatKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel5.setText("Kg");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel6.setText("Atur Diskon");

        sliderdiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderdiskonStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel8.setText("Jenis Jasa");

        btnjenisjasa.add(jreguler);
        jreguler.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jreguler.setText("Reguler");
        jreguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregulerActionPerformed(evt);
            }
        });

        btnjenisjasa.add(jexpress);
        jexpress.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jexpress.setText("Express");

        LDiskon.setText("0%");

        jLabel10.setText("jLabel10");

        jLabel11.setText("mouse moved at");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jreguler, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jexpress, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tnama)
                                .addComponent(jLabel3)
                                .addComponent(ttelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tberat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sliderdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LDiskon))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tberat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderdiskon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jreguler)
                    .addComponent(jexpress))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel9.setText("Total Harga");

        tatotal.setColumns(20);
        tatotal.setRows(5);
        jScrollPane1.setViewportView(tatotal);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        btnproses.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        btnproses.setText("Proses");
        btnproses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnprosesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnprosesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnprosesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnprosesMouseReleased(evt);
            }
        });
        btnproses.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                btnprosesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        btnulangi.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        btnulangi.setText("Ulangi");
        btnulangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnulangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnulangiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnulangiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnulangiMouseReleased(evt);
            }
        });
        btnulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnulangiActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bkeluarMouseExited(evt);
            }
        });
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnproses)
                .addGap(18, 18, 18)
                .addComponent(btnulangi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bkeluar)
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnulangi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnproses, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_bkeluarActionPerformed

    private void btnulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnulangiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnulangiActionPerformed

    private void jregulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregulerActionPerformed
        // TODO add your handling code here
          
    }//GEN-LAST:event_jregulerActionPerformed
 
 
    
    
    
    /*EVEN HANDLING 1*/
    
    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        Float VDiskon;
        Nama = tnama.getText();
        NoHp = ttelepon.getText();
        Diskon=sliderdiskon.getValue();
        if(jreguler.isSelected()){
            jenis=this.jreguler.getText();
            VDiskon= Float.valueOf(sliderdiskon.getValue());
            Total=11500*(Float.valueOf(tberat.getText()))-((Diskon*11500)/100);
            uang=Total;
            
        }
        else if(jexpress.isSelected()){
             jenis=this.jexpress.getText();
            VDiskon= Float.valueOf(sliderdiskon.getValue());
            Total=11500*(Float.valueOf(tberat.getText()))-((Diskon*11500)/100);
            uang=(Total*1.5f);
            
        }
         if (tnama.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Nama Anda Tidak Boleh Kosong\nSilahkan isi dulu","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
        }
          if (ttelepon.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Nomor Telepon Anda Tidak Boleh Kosong\nSilahkan isi dulu","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
        }
           if (tberat.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Berat Barang Anda Tidak Boleh Kosong\nSilahkan isi dulu","Informasi",
                JOptionPane.INFORMATION_MESSAGE);
    }
        tatotal.setText("|||||||=|TOTAL PEMBAYARAN||||||||"+
                          "\nNama \t: "+Nama+
                          "\nNo.Hp \t: "+NoHp+
                          "\nBerat Barang \t: "+tberat.getText()+"KG"+
                          "\nJenis \t: "+jenis+
                          "\nDiskon \t: "+Diskon+"%"+
                          "\nTotal \t: "+uang+"0" ); 
        
        
        
        
        
    }//GEN-LAST:event_btnprosesActionPerformed
/*EVEN HANDLING 2*/
    private void btnulangiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnulangiMousePressed
        // TODO add your handling code here:
        tnama.setText("");
        ttelepon.setText("");
        tatotal.setText("");
        tberat.setText("");
        sliderdiskon.setValue(0);
        btnjenisjasa.clearSelection();
    }//GEN-LAST:event_btnulangiMousePressed

/*EVEN HANDLING 3*/
    private void bkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseEntered
        // TODO add your handling code here:
        bkeluar.setBackground(Color.red);
        bkeluar.setForeground(Color.black);
        
    }//GEN-LAST:event_bkeluarMouseEntered
/*EVEN HANDLING 4*/
    private void bkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseExited
        // TODO add your handling code here:
        bkeluar.setBackground(Color.white);
        bkeluar.setForeground(Color.black);
    }//GEN-LAST:event_bkeluarMouseExited

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tnama.setText("");
        ttelepon.setText("");
        tatotal.setText("");
        tberat.setText("0");
    }//GEN-LAST:event_formWindowOpened

    /*EVEN HANDLING 5*/
    private void bkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bkeluarMouseClicked
        // TODO add your handling code here:
        int pilihan =JOptionPane.showConfirmDialog(this," Apa yakin anda ingin keluar","KELUAR?",JOptionPane.YES_NO_OPTION);
        if (pilihan==0){
            System.exit(0);
        }
    }//GEN-LAST:event_bkeluarMouseClicked

    private void btnprosesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprosesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprosesMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        setSize(670,560);
        setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void pheaderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pheaderMouseEntered
        // TODO add your handling code here:
       pheader.setBackground(Color.LIGHT_GRAY);
        pheader.setForeground(Color.black);
    }//GEN-LAST:event_pheaderMouseEntered

    private void pheaderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pheaderMouseExited
        // TODO add your handling code here:
         pheader.setBackground(Color.blue);
        pheader.setForeground(Color.black);
         
    }//GEN-LAST:event_pheaderMouseExited

    private void btnprosesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_btnprosesCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnprosesCaretPositionChanged

    private void tnamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tnamaCaretUpdate
        // TODO add your handling code here:
        if (tnama.getText().length()==0 && tberat.getText().length()!=0 && tberat.getText().matches("[0]")){
           btnproses.setEnabled(false);
        }
        else if (tnama.getText().length()!=0){
           btnproses.setEnabled(true);
        }
    }//GEN-LAST:event_tnamaCaretUpdate

    private void tteleponCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tteleponCaretUpdate
        // TODO add your handling code here:
        
        if (ttelepon.getText().length()==0 && !ttelepon.getText(). matches("[A-Z]") && !ttelepon.getText().matches("[a-z]")&& tberat.getText().matches("[0]") )  {
         btnproses.setEnabled(false);
        }
        else if (ttelepon.getText().length()!=0 && ttelepon.getText().matches("[1-9]")){
            btnproses.setEnabled(true);
        }
    }//GEN-LAST:event_tteleponCaretUpdate

    private void tberatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tberatCaretUpdate
        // TODO add your handling code here:
        Integer B;
        B = Integer.valueOf(tberat.getText());
        if(B==0){
            btnproses.setEnabled(false);
         }
        else if(B!=0){
            btnproses.setEnabled(true);
        }
    }//GEN-LAST:event_tberatCaretUpdate

    private void sliderdiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderdiskonStateChanged
        // TODO add your handling code here:
        LDiskon.setText(String.valueOf(sliderdiskon.getValue())+"%");
    }//GEN-LAST:event_sliderdiskonStateChanged

    private void tteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tteleponActionPerformed

    private void tteleponMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tteleponMouseReleased
        // TODO add your handling code here:
         int jumlah = Integer.valueOf(ttelepon.getText());
            
            if (jumlah<=10 && jumlah>12  ){
                JOptionPane.showMessageDialog(null, "Nomor telepon yang anda masukkan salah,mohon periksa kembali","Warning",JOptionPane.YES_OPTION);
                ttelepon.setText("");
            }else{
                
            }
         
    }//GEN-LAST:event_tteleponMouseReleased

    private void btnprosesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprosesMouseReleased
        // TODO add your handling code here:
        int jumlah = Integer.valueOf(ttelepon.getText());
            
            if (jumlah<=10 && jumlah>12  ){
                JOptionPane.showMessageDialog(null, "Nomor telepon yang anda masukkan salah,mohon periksa kembali","Warning",JOptionPane.YES_OPTION);
                ttelepon.setText("");
            }else{
                
            }
    }//GEN-LAST:event_btnprosesMouseReleased

    private void btnprosesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprosesMouseEntered
        // TODO add your handling code here:
        btnproses.setBackground(Color.blue);
         btnproses.setForeground(Color.black);
    }//GEN-LAST:event_btnprosesMouseEntered

    private void btnprosesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprosesMouseExited
        // TODO add your handling code here:
         btnproses.setBackground(Color.white);
         btnproses.setForeground(Color.black);
    }//GEN-LAST:event_btnprosesMouseExited

    private void btnulangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnulangiMouseEntered
        // TODO add your handling code here:
         btnulangi.setBackground(Color.yellow);
         btnulangi.setForeground(Color.black);
    }//GEN-LAST:event_btnulangiMouseEntered

    private void btnulangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnulangiMouseExited
        // TODO add your handling code here:
         btnulangi.setBackground(Color.white);
         btnulangi.setForeground(Color.black);
    }//GEN-LAST:event_btnulangiMouseExited

    private void btnulangiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnulangiMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnulangiMouseReleased

    /*EVEN HANDLING 6*/ 
    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        jLabel10.setText("(" +evt.getX() +","+evt.getY()+")");
        jLabel10.setLocation(evt.getX(),evt.getY());
    }//GEN-LAST:event_jPanel3MouseMoved

    
    /*EVEN HANDLING 7*/ 
    private void tnamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnamaKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_tnamaKeyTyped

    private void tteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tteleponKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_tteleponKeyTyped

    private void tberatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tberatKeyTyped
        // TODO add your handling code here:
        filterhuruff(evt);
    }//GEN-LAST:event_tberatKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSTTEST4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSTTEST4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDiskon;
    private javax.swing.JButton bkeluar;
    private javax.swing.ButtonGroup btnjenisjasa;
    private javax.swing.JButton btnproses;
    private javax.swing.JButton btnulangi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jexpress;
    private javax.swing.JRadioButton jreguler;
    private javax.swing.JPanel pheader;
    private javax.swing.JSlider sliderdiskon;
    private javax.swing.JTextArea tatotal;
    private javax.swing.JTextField tberat;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField ttelepon;
    // End of variables declaration//GEN-END:variables
}
